## 禁用重试调用功能
## feign 是在ribbon 和 hystrix 基础上封装的，所以ribbon的超时也是feign 的超时
timeout:
  connect: 300
  read: 12000

ribbon:
  ConnectTimeout: ${timeout.connect}
  ReadTimeout: ${timeout.read}
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 1000


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery:9182/eureka/

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

spring:
  rabbitmq:
    host: 47.105.143.13
    port: 5672
    username: jobs
    password: 123456
    virtual-host: /vconfig-uat


  datasource:
      url: jdbc:mysql://47.105.143.13:3307/testDb?characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      maxActive: 20
      initialSize: 1
      minIdle: 1
      filters: stat,slf4j

  redis:
    database: 0
    host: 47.105.143.13
    password:
    port: 6379
    timeout: 3000
    maxIdle: 8
    minIdle: 0
    maxActive: 8
    maxWait: -1

